name: Go
on: [push]
jobs:

  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: Build
        run: go build -v .
      - name: Test
        run: go test ./...

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
          with:
            go-version: 1.13
          id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: Test
        run: go test ./...

  vet:
    name: Vet
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
          with:
            go-version: 1.13
          id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: Vet
        run: go vet ./...